# Generated by Django 5.2.4 on 2025-07-20 21:38

import accounts.models
import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.MediaStorage(), upload_to=accounts.models.user_avatar_path),
        ),
    ]
