# Generated by Django 5.2.4 on 2025-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_outfit_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='times_worn',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='is_worn',
            field=models.BooleanField(default=False),
        ),
    ]
