# Generated by Django 5.2.4 on 2025-07-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_clothingitem_times_worn_clothingitem_is_worn'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL reference for external images', null=True),
        ),
    ]
