# Generated by Django 5.2.4 on 2025-08-01 05:44

import accounts.models
import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clothingitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.MediaStorage, upload_to=accounts.models.clothing_item_image_path),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.MediaStorage, upload_to=accounts.models.outfit_image_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.MediaStorage, upload_to=accounts.models.user_avatar_path),
        ),
    ]
