# Generated by Django 5.2.4 on 2025-08-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_clothingitem_image_alter_outfit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='accounts.clothingitem'),
        ),
    ]
